#!/bin/sh
#
#

delim="|"


netspeed() { \

SLP=1 # output / sleep interval
DEVICE=enp0s3
IS_GOOD=0
for GOOD_DEVICE in `grep \: /proc/net/dev | awk -F: '{print $1}'`; do
    if [ "$DEVICE" = $GOOD_DEVICE ]; then
        IS_GOOD=1
        break
    fi
done

if [ $IS_GOOD -eq 0 ]; then
    echo "Device not found. Should be one of these:"
        grep ":" /proc/net/dev | awk -F: '{print $1}' | sed s@\ @@g 
    exit 1
fi

LINE=`grep $DEVICE /proc/net/dev | sed s/.*://`;
RECEIVED1=`echo $LINE | awk '{print $1}'`
TRANSMITTED1=`echo $LINE | awk '{print $9}'`
TOTAL=$(($RECEIVED1+$TRANSMITTED1))

sleep $SLP

LINE=`grep $DEVICE /proc/net/dev | sed s/.*://`;
RECEIVED2=`echo $LINE | awk '{print $1}'`
TRANSMITTED2=`echo $LINE | awk '{print $9}'`
SPEED=$((($RECEIVED2+$TRANSMITTED2-$TOTAL)/$SLP))
INSPEED=$((($RECEIVED2-$RECEIVED1)/$SLP))
OUTSPEED=$((($TRANSMITTED2-$TRANSMITTED1)/$SLP))

printf "u: %3i KB/s d: %3i KB/s" $(($INSPEED/1024)) $(($OUTSPEED/1024)) ;

}

testweather() { \

	[ "$(stat -c %y "$HOME/.local/share/weatherreport" 2>/dev/null | cut -d ' ' -f1)" != "$(date '+%Y-%m-%d')" ] &&
	ping -q -c 1 1.1.1.1 >/dev/null &&
	curl -s "https://wttr.in/Moscow?0TQ&lang=ru" -o "$HOME/.local/share/weatherreport" &&
	notify-send "Weather" "New weather forecast today." &&
	refbar
}


status() { \

	[ "$(stat -c %y "$HOME/.local/share/weatherreport" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] &&
		weather=$(cat "$HOME/.local/share/weatherreport" | head -2 | cut -c 17- | tr '  ' ' ' | tr '\n' ' ' | sed 's/[[:blank:]]*$//')

	LT=$(date "+%b %d %Y %a %H:%M")
	mem=$(free -m | awk '/^Mem:/ {print $3 "/" $2}')
	netw=$(netspeed)

	#echo "$delim Wthr: $weather $delim Krnl:$(uname -r) $delim Net: $netw $delim Mem:$mem $delim $LT $delim"
	echo "$delim Pkgs: $(qlist -I | wc -l) $delim Krnl:$(uname -r) $delim Net: $netw $delim Mem:$mem $delim $LT $delim"
}

testweather &
xsetroot -name "$(status | tr '\n' ' ')"
