.TH Config HerbstLuftWM 8 "16 jun 2023"

.SH NAME

Config HerbstLuftWM

.SH SYNOPSIS

	Мой конфигурацинный файл WM

.SH DESCRIPTION
.PP
Описание сокращений и быстрых клавиш в WM HersbtLuftWM

Клавиши модификаторы:
 Mod - Win кнопка
 Mod1 - Alt кнопка

.SH OPTIONS
.SS Комманды:
.SS Системные комманды:
.PP
.TP
Перезагрузить конфигурацию herbstluftwm

 Win-Control-r
.PP
.TP
Закрыть текущее окно

 Win-Shift-c 
.PP
.TP
Выйти из WM

 Win-Shift-q 

.SH 1 Основные команды
.PP
.TP
Запуск терминала (или по переменной TERMINAL):

 Win-Shift-Return
.PP
.TP
Запуск меню в верхней строке:

 Alt-Shift-Return

.SH 2 Справочные команды
.PP
.TP
Посмотреть текущую погоду:

 Alt-Shift-i

.PP
.TP
Смотрим список десктопов с их номерами:

 Alt-Shift-h

.PP
.SS Сделать скриншот экрана (и поместить его в ~/screenshots)

 Win-Shift-p

.PP
.SS Запуск браузеров (запуск на столе - www (3)):

 Win-Shift-b -->>  vimb
 Win-Shift-n -->> qutebrowser
 Win-Shift-f -->> firefox

.PP
.SS Мультимедия : # Media keys

 [Fn] + [<-] - уменьшение громкости на 5
 [Fn] + [->] - увеличение громкости на 5
 [Fn] + [Up]   - увеличение яркости экрана
 [Fn] + [Down] - уменьшение яркости экрана

.SH 3  Управляющие сочетания клавиш:
.PP
.SS перемещение фокуса между окнами

 Win-Left	-	фокус на левое окно
 Win-Right	- 	фокус на правое окно
 Win-Up		- 	фокус на окно сверху
 Win-Down	- 	фокус на окно снизу

.PP
.SS перемещение окон

 Win-Shift-Down		-	сдвинуть окно вниз
 Win-Shift-Up		-	сдвинуть окно вверх
 Win-Shift-Rightш	- 	сдвинуть окно вправо
.PP
.SS управление тайлингом:

 Win-u	- разделить экран на 2 части снизу от текущего экрана
 Win-o	- разделить экран на 2 части справа от текущего экрана
 
 Win-Control-space	- разбить экраны
 Win-Control-Left	- увеличить границы экрана слева
 Win-Control-Down	- увеличить границы экрана снизу
 Win-Control-Up		- увеличить границы экрана сверху
 Win-Control-Right	- увеличить границы экрана справа

 Win-r                   - удалить экран
 Win-f	                 - распахнуть экран на всю область
 Win-Shift-f             - установить текущее окно в режим плавающего окна
 Win-p			 - установить текущее окно в режим псевдотайла
 Win-space		- переключение режима тайлинга в текущей области
 Win-BackSpace	        - переключение режима тайлинга в текущей области
 Win-Tab		 - переключение фокуса между окнами
 Win-Shift-Tab		- переключение фокуса между окнами в обратном порядке
 Win-c			- циклическое перемещение фокуса между окнами внути области
 Win-i		        - перемещение фокуса на установленный тэг окна urgent
.SH AUTHOR
Stas Nizhnichenko (dradmin (at) rambler.ru)
