#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.
xset fp rehash

xset -b #disable bell

if test -f $HOME/.Xresources
then
	xrdb -merge $HOME/.Xresources
fi

xmodmap $HOME/.Xmodmap

setxkbmap -layout "us,ru" -option "grp:alt_shift_toggle,grp_led:scroll"

feh --bg-scale $HOME/Wallpapers/1.png
dunst &

xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55 &
#picom -b --config $HOME/.config/picom/picom.conf

xset r rate 300 50 &

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &


# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

fluxbox &
fbpid=$!

sleep 1
{
   # Applications you want to run after fluxbox has started
   # MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN & AT THE END.
   # ipager &
   # gkrellm2 &
   #nm-applet &
   feh --bg-scale $HOME/Wallpapers/1.png
} &
 
wait $fbpid

# or if you want to keep a log:
# exec fluxbox -log "/root/.fluxbox/log"

